import { LightningElement } from 'lwc';
import { ShowToastEvent } from 'lightning/platformShowToastEvent';
import getServices from '@salesforce/apex/LadminAIAppointmentServiceCatalog.getServices';
import saveService from '@salesforce/apex/LadminAIAppointmentServiceCatalog.saveService';
import setActive from '@salesforce/apex/LadminAIAppointmentServiceCatalog.setActive';
import importServices from '@salesforce/apex/LadminAIAppointmentServiceCatalog.importServices';
export default class LadminAiServiceCatalog extends LightningElement {
    services=[]; loading=true; error; importErrors=[]; editing=false; draft={};
    connectedCallback(){this.load();}
    get empty(){return !this.loading&&!this.services.length;} get hasImportErrors(){return this.importErrors.length>0;} get dialogTitle(){return this.draft.id?'Edit Service':'Add Service';}
    async load(){this.loading=true;this.error=null;try{const rows=await getServices();this.services=rows.map(r=>({...r,status:r.Active__c?'Active':'Inactive',toggleLabel:r.Active__c?'Deactivate':'Activate'}));}catch(e){this.error=this.message(e);}finally{this.loading=false;}}
    create(){this.draft={id:null,name:'',duration:30,before:0,after:0,description:'',active:true};this.editing=true;}
    edit(e){const r=this.services.find(x=>x.Id===e.currentTarget.dataset.id);this.draft={id:r.Id,name:r.Name,duration:r.Duration_Minutes__c,before:r.Buffer_Before_Minutes__c,after:r.Buffer_After_Minutes__c,description:r.Description__c,active:r.Active__c};this.editing=true;}
    close(){this.editing=false;} change(e){this.draft={...this.draft,[e.target.name]:e.target.type==='checkbox'?e.target.checked:e.target.value};}
    async save(){try{await saveService({serviceId:this.draft.id,name:this.draft.name,durationMinutes:this.draft.duration,bufferBefore:this.draft.before,bufferAfter:this.draft.after,description:this.draft.description,active:this.draft.active});this.close();await this.load();}catch(e){this.error=this.message(e);}}
    async toggle(e){const r=this.services.find(x=>x.Id===e.currentTarget.dataset.id);try{await setActive({serviceId:r.Id,active:!r.Active__c});await this.load();}catch(x){this.error=this.message(x);}}
    exportCsv(){const rows=[['Name','Duration Minutes','Buffer Before','Buffer After','Description','Active'],...this.services.map(r=>[r.Name,r.Duration_Minutes__c,r.Buffer_Before_Minutes__c,r.Buffer_After_Minutes__c,r.Description__c||'',r.Active__c])];const csv=rows.map(row=>row.map(value=>`"${String(value).replaceAll('"','""')}"`).join(',')).join('\r\n');const link=document.createElement('a');link.href=`data:text/csv;charset=utf-8,${encodeURIComponent(csv)}`;link.download='ladminai-service-catalog.csv';link.click();}
    async importCsv(event){const file=event.target.files?.[0];if(!file)return;this.error=null;this.importErrors=[];this.loading=true;try{const text=await file.text();const rows=this.parseCsv(text);if(rows.length<2)throw new Error('The CSV does not contain any service rows.');const expected=['name','duration minutes','buffer before','buffer after','description','active'];const headers=rows[0].map(x=>x.trim().toLowerCase());if(expected.some((name,index)=>headers[index]!==name))throw new Error('Use the exported CSV columns without renaming or reordering them.');const inputRows=rows.slice(1).filter(row=>row.some(value=>value.trim())).map(row=>({name:row[0],durationMinutes:Number(row[1]),bufferBefore:Number(row[2]||0),bufferAfter:Number(row[3]||0),description:row[4],active:String(row[5]).trim().toLowerCase()==='true'}));const result=await importServices({inputRows});this.importErrors=result.errors||[];await this.load();this.dispatchEvent(new ShowToastEvent({title:'Service import complete',message:`${result.imported} service rows imported.`,variant:this.importErrors.length?'warning':'success'}));}catch(e){this.error=this.message(e);}finally{this.loading=false;event.target.value=null;}}
    parseCsv(text){const rows=[];let row=[],field='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){field+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){row.push(field);field='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(field);rows.push(row);row=[];field='';}else field+=c;}if(field||row.length){row.push(field);rows.push(row);}return rows;}
    message(e){return e?.body?.message||e?.message||'The service catalogue could not be updated.';}
}
