import { LightningElement } from 'lwc';
import getAppointments from '@salesforce/apex/LadminAIAppointmentCommandService.getAppointments';
import getSlots from '@salesforce/apex/LadminAIAppointmentAvailabilityService.getAvailableSlots';
import reschedule from '@salesforce/apex/LadminAIAppointmentCommandService.reschedule';
import cancel from '@salesforce/apex/LadminAIAppointmentCommandService.cancel';
import updateStatus from '@salesforce/apex/LadminAIAppointmentCommandService.updateStatus';
const ALL='ALL';
export default class LadminAiAppointmentCalendar extends LightningElement{
 rows=[];error;loading=true;selected;action;date;slots=[];time;reason='';status='Confirmed';searchTerm='';viewMode='all';resourceFilter=ALL;locationFilter=ALL;statusFilter=ALL;bookedByFilter=ALL;startDate;endDate;
 connectedCallback(){this.setDefaultDates();this.load();}
 setDefaultDates(){const today=new Date(),start=new Date(today),end=new Date(today);start.setDate(start.getDate()-90);end.setDate(end.getDate()+90);this.startDate=this.dateValue(start);this.endDate=this.dateValue(end);}
 get today(){return new Date().toISOString().slice(0,10);} get totalCount(){return this.rows.length;} get filteredCount(){return this.filteredRows.length;} get hasRows(){return this.filteredRows.length>0;} get isDetails(){return this.action==='details';} get isReschedule(){return this.action==='reschedule';} get isCancel(){return this.action==='cancel';} get isStatus(){return this.action==='status';} get hasSaveAction(){return !this.isDetails;} get dialogTitle(){return this.isDetails?'Appointment Details':this.isReschedule?'Reschedule Appointment':this.isCancel?'Cancel Appointment':'Update Appointment Status';}
 get saveDisabled(){return(this.isReschedule&&(!this.date||!this.time))||(this.isCancel&&!this.reason.trim());} get slotOptions(){return this.slots.map(s=>({label:`${s[0]} – ${s[1]}`,value:s[0]}));}
 get statusOptions(){return['Booked','Confirmed','Checked In','In Progress','Arrived','Completed','No Show'].map(v=>({label:v,value:v}));} get filterStatusOptions(){return[{label:'All statuses',value:ALL},...this.optionsFor('status')];} get viewOptions(){return[{label:'All appointments',value:'all'},{label:'Upcoming',value:'upcoming'},{label:'Past / history',value:'past'}];} get resourceOptions(){return[{label:'All resources',value:ALL},...this.optionsFor('resourceName')];} get locationOptions(){return[{label:'All locations',value:ALL},...this.optionsFor('locationName')];} get bookedByOptions(){return[{label:'All booking users',value:ALL},...this.optionsFor('bookedBy')];}
 optionsFor(field){return[...new Set(this.rows.map(r=>r[field]).filter(Boolean))].sort((a,b)=>a.localeCompare(b)).map(v=>({label:v,value:v}));}
 get filteredRows(){const q=this.searchTerm.trim().toLowerCase(),now=Date.now();return this.rows.filter(r=>{const scheduled=new Date(r.startUtc).getTime();return(this.viewMode==='all'||(this.viewMode==='upcoming'&&scheduled>=now)||(this.viewMode==='past'&&scheduled<now))&&(this.resourceFilter===ALL||r.resourceName===this.resourceFilter)&&(this.locationFilter===ALL||r.locationName===this.locationFilter)&&(this.statusFilter===ALL||r.status===this.statusFilter)&&(this.bookedByFilter===ALL||r.bookedBy===this.bookedByFilter)&&(!q||[r.name,r.subject,r.leadName,r.resourceName,r.locationName,r.bookedBy,r.status].some(v=>(v||'').toLowerCase().includes(q)));}).sort((a,b)=>(this.viewMode==='upcoming'?1:-1)*(new Date(a.startUtc)-new Date(b.startUtc)));}
 async load(){this.loading=true;this.error=null;try{const data=await getAppointments({startDate:this.startDate||null,endDate:this.endDate||null});this.rows=data.map(r=>({...r,subject:r.subject||r.name||'Appointment',leadName:r.leadName||'Not specified',resourceName:r.resourceName||'Unassigned',locationName:r.locationName||'Not specified',bookedBy:r.bookedBy||'Unattributed',status:r.status||'Not set',statusClass:this.statusClass(r.status)}));}catch(e){this.error=e?.body?.message||'Appointments could not be loaded.';this.rows=[];}finally{this.loading=false;}}
 statusClass(value){const status=(value||'').toLowerCase();return status.includes('cancel')?'pill pill_cancelled':status==='no show'?'pill pill_attention':status==='completed'?'pill pill_completed':'pill pill_active';} dateValue(value){return value.toISOString().slice(0,10);} changeSearch(e){this.searchTerm=e.target.value||'';} changeFilter(e){this[e.target.dataset.field]=e.detail?.value??e.target.value;} async resetFilters(){this.searchTerm='';this.viewMode='all';this.resourceFilter=ALL;this.locationFilter=ALL;this.statusFilter=ALL;this.bookedByFilter=ALL;this.setDefaultDates();await this.load();}
 open(e){this.openAction(e.currentTarget.dataset.id,e.currentTarget.dataset.action);} openMenu(e){this.openAction(e.currentTarget.dataset.id,e.detail.value);} openAction(id,action){this.selected=this.rows.find(r=>r.id===id);this.action=action;this.date=null;this.time=null;this.reason='';this.slots=[];} close(){this.action=null;this.selected=null;} async changeDate(e){this.date=e.target.value;this.slots=await getSlots({serviceResourceId:this.selected.resourceId,locationId:this.selected.locationId,targetDate:this.date});} change(e){this[e.target.name]=e.detail?.value??e.target.value;}
 async submit(){try{if(this.isReschedule)await reschedule({appointmentId:this.selected.id,targetDate:this.date,startTime:this.time});if(this.isCancel)await cancel({appointmentId:this.selected.id,reason:this.reason});if(this.isStatus)await updateStatus({appointmentId:this.selected.id,status:this.status});this.close();await this.load();}catch(e){this.error=e?.body?.message||e?.message||'The appointment could not be updated.';}}
}
