import { api, LightningElement } from 'lwc';
import { ShowToastEvent } from 'lightning/platformShowToastEvent';
import getAppointments from '@salesforce/apex/LadminAIAppointmentCommandService.getAppointments';
import getSlots from '@salesforce/apex/LadminAIAppointmentAvailabilityService.getAvailableSlots';
import getLocations from '@salesforce/apex/LadminAIAppointmentLocationService.getActiveLocations';
import getResources from '@salesforce/apex/LadminAIAppointmentLocationService.getDoctorsForLocation';
import rescheduleTo from '@salesforce/apex/LadminAIAppointmentCommandService.rescheduleTo';
import cancel from '@salesforce/apex/LadminAIAppointmentCommandService.cancel';
import updateStatus from '@salesforce/apex/LadminAIAppointmentCommandService.updateStatus';
import bulkUpdateStatus from '@salesforce/apex/LadminAIAppointmentCommandService.bulkUpdateStatus';
import getCancellationReasons from '@salesforce/apex/LadminAIAppointmentCommandService.getCancellationReasons';
const ALL='ALL';
export default class LadminAiAppointmentCalendar extends LightningElement{
 rows=[];error;loading=true;selected;action;actionMenuId;date;slots=[];time;reason='';status='Confirmed';bulkStatus='Confirmed';selectedIds=[];cancellationReasons=[];searchTerm='';viewMode='all';resourceFilter=ALL;locationFilter=ALL;statusFilter=ALL;bookedByFilter=ALL;startDate;endDate;rescheduleLocations=[];rescheduleResources=[];rescheduleLocationId;rescheduleResourceId;choicesLoading=false;slotsLoading=false;slotMessage;actionError;saving=false;
 connectedCallback(){this.setDefaultDates();this.load();}
 setDefaultDates(){const today=new Date(),start=new Date(today),end=new Date(today);start.setDate(start.getDate()-90);end.setDate(end.getDate()+90);this.startDate=this.dateValue(start);this.endDate=this.dateValue(end);}
 get today(){return new Date().toISOString().slice(0,10);} get totalCount(){return this.rows.length;} get filteredCount(){return this.filteredRows.length;} get hasRows(){return this.filteredRows.length>0;} get isDetails(){return this.action==='details';} get isReschedule(){return this.action==='reschedule';} get isCancel(){return this.action==='cancel';} get isStatus(){return this.action==='status';} get hasSaveAction(){return !this.isDetails;} get dialogTitle(){return this.isDetails?'Appointment Details':this.isReschedule?'Reschedule Appointment':this.isCancel?'Cancel Appointment':'Update Appointment Status';}
 get saveDisabled(){return this.saving||(this.isReschedule&&(!this.rescheduleLocationId||!this.rescheduleResourceId||!this.date||!this.time))||(this.isCancel&&!this.reason.trim());} get saveLabel(){return this.saving?'Saving…':'Save';} get slotOptions(){return this.slots.map(s=>({label:`${s[0]} – ${s[1]}`,value:s[0]}));} get rescheduleLocationOptions(){return this.rescheduleLocations.map(v=>({label:v.Name,value:v.Id}));} get rescheduleResourceOptions(){return this.rescheduleResources.map(v=>({label:v.Name,value:v.Id}));}
 get statusOptions(){return['Booked','Confirmed','Checked In','In Progress','Arrived','Completed','No Show'].map(v=>({label:v,value:v}));} get filterStatusOptions(){return[{label:'All statuses',value:ALL},...this.optionsFor('status')];} get viewOptions(){return[{label:'All appointments',value:'all'},{label:'Upcoming',value:'upcoming'},{label:'Past / history',value:'past'}];} get resourceOptions(){return[{label:'All resources',value:ALL},...this.optionsFor('resourceName')];} get locationOptions(){return[{label:'All locations',value:ALL},...this.optionsFor('locationName')];} get bookedByOptions(){return[{label:'All booking users',value:ALL},...this.optionsFor('bookedBy')];}
 optionsFor(field){return[...new Set(this.rows.map(r=>r[field]).filter(Boolean))].sort((a,b)=>a.localeCompare(b)).map(v=>({label:v,value:v}));}
 get filteredRows(){const q=this.searchTerm.trim().toLowerCase(),now=Date.now();return this.rows.filter(r=>{const scheduled=new Date(r.startUtc).getTime();return(this.viewMode==='all'||(this.viewMode==='upcoming'&&scheduled>=now)||(this.viewMode==='past'&&scheduled<now))&&(this.resourceFilter===ALL||r.resourceName===this.resourceFilter)&&(this.locationFilter===ALL||r.locationName===this.locationFilter)&&(this.statusFilter===ALL||r.status===this.statusFilter)&&(this.bookedByFilter===ALL||r.bookedBy===this.bookedByFilter)&&(!q||[r.name,r.subject,r.leadName,r.resourceName,r.locationName,r.bookedBy,r.status].some(v=>(v||'').toLowerCase().includes(q)));}).sort((a,b)=>(this.viewMode==='upcoming'?1:-1)*(new Date(a.startUtc)-new Date(b.startUtc))).map(r=>({...r,showActionMenu:r.id===this.actionMenuId}));}
 async load(){this.loading=true;this.error=null;try{const [data,reasons]=await Promise.all([getAppointments({startDate:this.startDate||null,endDate:this.endDate||null}),getCancellationReasons()]);this.cancellationReasons=(reasons||[]).map(value=>({label:value,value}));this.rows=data.map(r=>({...r,subject:r.subject||r.name||'Appointment',leadName:r.leadName||'Not specified',resourceName:r.resourceName||'Unassigned',locationName:r.locationName||'Not specified',bookedBy:r.bookedBy||'Unattributed',status:r.status||'Not set',statusClass:this.statusClass(r.status)}));}catch(e){this.error=e?.body?.message||'Appointments could not be loaded.';this.rows=[];}finally{this.loading=false;}}
 statusClass(value){const status=(value||'').toLowerCase();return status.includes('cancel')?'pill pill_cancelled':status==='no show'?'pill pill_attention':status==='completed'?'pill pill_completed':'pill pill_active';} dateValue(value){return value.toISOString().slice(0,10);} changeSearch(e){this.searchTerm=e.target.value||'';} changeFilter(e){this[e.target.dataset.field]=e.detail?.value??e.target.value;} async resetFilters(){this.searchTerm='';this.viewMode='all';this.resourceFilter=ALL;this.locationFilter=ALL;this.statusFilter=ALL;this.bookedByFilter=ALL;this.setDefaultDates();await this.load();}
 open(e){this.openAction(e.currentTarget.dataset.id,e.currentTarget.dataset.action);} openMenu(e){this.openAction(e.currentTarget.dataset.id,e.detail.value);} async openAction(id,action){this.selected=this.rows.find(r=>r.id===id);this.action=action;this.date=null;this.time=null;this.reason='';this.slots=[];this.slotMessage=null;this.actionError=null;this.error=null;if(action==='reschedule'){this.choicesLoading=true;try{await this.loadRescheduleChoices();}finally{this.choicesLoading=false;}}} close(){if(this.saving)return;this.action=null;this.selected=null;this.actionError=null;} async loadRescheduleChoices(){try{this.rescheduleLocations=await getLocations();this.rescheduleLocationId=this.rescheduleLocations.some(v=>v.Id===this.selected.locationId)?this.selected.locationId:(this.rescheduleLocations[0]?.Id||null);await this.loadRescheduleResources();}catch(e){this.actionError=e?.body?.message||'Active scheduling choices could not be loaded.';}} async loadRescheduleResources(){this.rescheduleResources=this.rescheduleLocationId?await getResources({locationId:this.rescheduleLocationId}):[];this.rescheduleResourceId=this.rescheduleResources.some(v=>v.Id===this.selected.resourceId)?this.selected.resourceId:(this.rescheduleResources[0]?.Id||null);this.date=null;this.time=null;this.slots=[];this.slotMessage=this.rescheduleResources.length?null:'No active service resource is assigned to this location.';} async changeRescheduleLocation(e){this.actionError=null;this.choicesLoading=true;this.rescheduleLocationId=e.detail.value;try{await this.loadRescheduleResources();}finally{this.choicesLoading=false;}} changeRescheduleResource(e){this.actionError=null;this.rescheduleResourceId=e.detail.value;this.date=null;this.time=null;this.slots=[];this.slotMessage=null;} async changeDate(e){if(this.choicesLoading||!this.rescheduleLocationId||!this.rescheduleResourceId)return;this.actionError=null;this.date=e.target.value;this.time=null;this.slots=[];this.slotMessage=null;this.slotsLoading=true;try{this.slots=await getSlots({serviceResourceId:this.rescheduleResourceId,locationId:this.rescheduleLocationId,targetDate:this.date});if(!this.slots.length)this.slotMessage='No available times for this date. Choose another date or configure availability for this resource.';}catch(x){this.slotMessage=x?.body?.message||'Available times could not be loaded.';}finally{this.slotsLoading=false;}} change(e){this.actionError=null;this[e.target.name]=e.detail?.value??e.target.value;}
 async submit(){if(this.saveDisabled)return;this.saving=true;this.actionError=null;const completedAction=this.action;try{if(this.isReschedule)await rescheduleTo({appointmentId:this.selected.id,locationId:this.rescheduleLocationId,resourceId:this.rescheduleResourceId,targetDate:this.date,startTime:this.time});if(this.isCancel)await cancel({appointmentId:this.selected.id,reason:this.reason});if(this.isStatus)await updateStatus({appointmentId:this.selected.id,status:this.status});this.saving=false;this.close();await this.load();const messages={reschedule:'Appointment rescheduled successfully.',cancel:'Appointment cancelled successfully.',status:'Appointment status updated successfully.'};this.dispatchEvent(new ShowToastEvent({title:'Appointment updated',message:messages[completedAction],variant:'success'}));}catch(e){this.actionError=e?.body?.message||e?.message||'The appointment could not be updated.';}finally{this.saving=false;}}
 toggleActionMenu(e){const id=e.currentTarget.dataset.id;this.actionMenuId=this.actionMenuId===id?null:id;}
 chooseAction(e){const id=e.currentTarget.dataset.id,action=e.currentTarget.dataset.action;this.actionMenuId=null;this.openAction(id,action);}
 @api selectFirstRescheduleSlot(){if(!this.slots.length)throw new Error('No available reschedule slot can be selected.');this.time=this.slots[0][0];return this.time;}
 @api hasRescheduleSlots(){return !this.slotsLoading&&this.slots.length>0;}
 @api selectDialogStatus(value){if(!this.statusOptions.some(option=>option.value===value))throw new Error('Unsupported appointment status.');this.status=value;return this.status;}
 changeSelection(e){const id=e.target.dataset.id;this.selectedIds=e.target.checked?[...new Set([...this.selectedIds,id])]:this.selectedIds.filter(value=>value!==id);}
 changeBulkStatus(e){this.bulkStatus=e.detail.value;}
 async applyBulkStatus(){if(!this.selectedIds.length)return;this.saving=true;this.error=null;try{await bulkUpdateStatus({appointmentIds:this.selectedIds,status:this.bulkStatus});this.selectedIds=[];await this.load();}catch(e){this.error=e?.body?.message||'Bulk status update failed.';}finally{this.saving=false;}}
 get bulkDisabled(){return this.saving||!this.selectedIds.length;}
}
